import 'dart:io';
import 'package:test/test.dart';

// Package root is one level up from the test/ directory.
final _packageRoot = Directory.current.path.endsWith('/test')
    ? Directory.current.parent.path
    : Directory.current.path;

void _writeIosConfigFileSpec(Directory dir) {
  File('${dir.path}/annspec.yaml').writeAsStringSync('''
enabled: true
app:
  integrations:
    firebase: true
  android:
    default:
      id: com.example.test
      sdk:
        minSdk: 24
        compileSdk: 35
        targetSdk: 35
    flavor:
      app:
        name: "Test App"
        main_file: "lib/main.dart"
        version_name: "1.0.0"
        version_code: 100000
        id_suffix: .app
  ios:
    default:
      id: com.example.test
    flavor:
      app:
        name: "Test App"
        main_file: "lib/main.dart"
        version_name: "1.0.0"
        version_code: 100000
        id_suffix: .app
        build_types:
          release:
            firebase:
              config_file: "keys/GoogleService-Info.plist"
''');
}

Future<ProcessResult> _runSync(Directory projectDir, {String? firebaseMode}) {
  final args = ['run', 'ann_flutter_flavor', 'sync', '--project', projectDir.path];
  if (firebaseMode != null) args.addAll(['--firebase-mode', firebaseMode]);
  return Process.run('dart', args, workingDirectory: _packageRoot);
}

void _writeProjectIdSpec(Directory dir) {
  File('${dir.path}/annspec.yaml').writeAsStringSync('''
enabled: true
app:
  integrations:
    firebase: true
  android:
    default:
      id: com.example.test
      sdk:
        minSdk: 24
        compileSdk: 35
        targetSdk: 35
    flavor:
      app:
        name: "Test App"
        main_file: "lib/main.dart"
        version_name: "1.0.0"
        version_code: 100000
        id_suffix: .app
  ios:
    default:
      id: com.example.test
    flavor:
      app:
        name: "Test App"
        main_file: "lib/main.dart"
        version_name: "1.0.0"
        version_code: 100000
        id_suffix: .app
        build_types:
          release:
            firebase:
              project_id: "my-firebase-prod"
''');
}

void main() {
  group('firebase_generator — iOS config_file guard', () {
    late Directory tempDir;

    setUp(() => tempDir = Directory.systemTemp.createTempSync('fbgen_test_'));
    tearDown(() => tempDir.deleteSync(recursive: true));

    test('sync exits 1 when iOS firebase block uses config_file', () async {
      _writeIosConfigFileSpec(tempDir);
      final result = await _runSync(tempDir);
      expect(result.exitCode, 1,
          reason: 'stderr: ${result.stderr}\nstdout: ${result.stdout}');
    });

    test('sync error mentions config_file is Android-only', () async {
      _writeIosConfigFileSpec(tempDir);
      final result = await _runSync(tempDir);
      final output = '${result.stdout}${result.stderr}';
      expect(
        output.toLowerCase(),
        anyOf(
          contains('android-only'),
          contains('config_file'),
          contains('project_id'),
        ),
        reason: 'Expected error mentioning config_file/Android-only, got: $output',
      );
    });

    test('no firebase options dart file generated when iOS config_file aborts step 4', () async {
      _writeIosConfigFileSpec(tempDir);
      await _runSync(tempDir);
      // Firebase options files (generated by flutterfire configure) must not exist.
      // Step 1 Dart codegen may still produce ann_flavor.g.dart — that is expected.
      final firebaseDir = Directory('${tempDir.path}/lib/generated/firebase');
      expect(
        firebaseDir.existsSync() && firebaseDir.listSync().isNotEmpty,
        isFalse,
        reason: 'No firebase options files should be generated when iOS config_file aborts step 4',
      );
    });
  });

  group('firebase_generator — script mode', () {
    late Directory tempDir;

    setUp(() => tempDir = Directory.systemTemp.createTempSync('fbscript_test_'));
    tearDown(() => tempDir.deleteSync(recursive: true));

    test('--firebase-mode script generates firebase.sh', () async {
      _writeProjectIdSpec(tempDir);
      final result = await _runSync(tempDir, firebaseMode: 'script');
      expect(result.exitCode, 0,
          reason: 'stderr: ${result.stderr}\nstdout: ${result.stdout}');
      final scriptFile = File('${tempDir.path}/lib/generated/scripts/firebase.sh');
      expect(scriptFile.existsSync(), isTrue,
          reason: 'lib/generated/scripts/firebase.sh should be created');
    });

    test('--firebase-mode script writes flutterfire configure commands', () async {
      _writeProjectIdSpec(tempDir);
      await _runSync(tempDir, firebaseMode: 'script');
      final content = File('${tempDir.path}/lib/generated/scripts/firebase.sh').readAsStringSync();
      expect(content, contains('flutterfire configure'));
      expect(content, contains('my-firebase-prod'));
      expect(content, contains('SCRIPT_DIR'));
    });

    test('--firebase-mode script does not run flutterfire inline', () async {
      _writeProjectIdSpec(tempDir);
      final result = await _runSync(tempDir, firebaseMode: 'script');
      // In script mode, sync should never exec flutterfire; stdout must not
      // contain messages that indicate an inline run.
      expect(result.stdout, isNot(contains('Running flutterfire')));
    });
  });
}
